import React from 'react';
import Seo from '@/components/Seo';

const S = ({ title, children }) => (
  <section style={{ marginBottom: 26 }}>
    <h2 style={{ fontSize: 20, margin: '0 0 8px' }}>{title}</h2>
    <div style={{ fontSize: 14.5, lineHeight: 1.65, color: 'var(--color-neutral-800)' }}>{children}</div>
  </section>
);

export default function Privacy() {
  return (
    <section style={{ padding: 'clamp(28px,6vh,64px) 0 clamp(36px,6vh,64px)', maxWidth: '68ch' }}>
      <Seo
        title="Privacy Policy | Pathways"
        description="How Pathways handles student information. We never sell student data, and our handling is aligned with COPPA and FERPA expectations."
        path="/privacy"
      />
      {/* Tag removed: it said "Privacy" directly above a heading reading
          "Privacy Policy". */}
      <h1 style={{ fontSize: 'clamp(30px,4.2vw,46px)', margin: '0 0 8px' }}>Privacy Policy</h1>
      <p style={{ color: 'var(--color-neutral-600)', fontSize: 13, marginBottom: 28 }}>
        Last updated August 2026
      </p>

      <S title="Who we are">
        Pathways is a free platform that connects high school students with students, educators, and counselors who
        can give firsthand guidance on college and careers. This policy explains what we collect and what we do with it.
      </S>

      <S title="What we collect">
        When you create an account we receive your name and email address from your sign-in provider. When you complete
        your profile we store what you tell us: your role, grade, school, topics you want help with, and anything you
        write in your bio. We store the posts and messages you choose to send, and the questions you ask Sage so your
        conversation is there when you come back.
      </S>

      <S title="What we do not do">
        We do not sell student data. We do not sell or share your information with data brokers, and we do not use your
        messages or Sage conversations to advertise to you. Sage subscribers see no college advertising anywhere in
        the app.
      </S>

      <S title="How we use what we collect">
        We use your profile to match you with relevant people and posts, to let other members find you when you want to
        be found, and to give Sage enough context to answer usefully. We use your email to sign you in and to send
        account-related messages.
      </S>

      <S title="Who can see your information">
        Your name, headline, school, bio, and topics are visible to other signed-in Pathways members so they can decide
        whether to connect with you. Your direct messages are visible only to you and the person you are messaging.
        Your Sage conversations are visible only to you.
      </S>

      <S title="Third parties">
        Pathways runs on Base44, which hosts our application and database and handles authentication. Sign-in is
        provided through Google. Sage answers are generated by a large language model provider. These providers process
        data on our behalf under their own terms.
      </S>

      <S title="Students under 18">
        Pathways is intended for people 14 and older. We align our handling of student information with COPPA and FERPA
        expectations. If you believe a child under 14 has created an account, contact us and we will remove it.
      </S>

      <S title="Your choices">
        You can edit or clear the information on your profile at any time from the Profile tab. You can request deletion
        of your account and its associated data by contacting us at the address below, and we will action it.
      </S>

      <S title="Contact">
        Questions about this policy can be sent to <b>ishaanshah101@gmail.com</b>.
      </S>
    </section>
  );
}
