import React, { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { useProfile } from '@/lib/useProfile';
import { useSubscription, openBillingPortal } from '@/lib/useSubscription';
import SagePaywall from '@/components/app/SagePaywall';
import { Spinner } from '@/components/RequireAuth';
import Seo from '@/components/Seo';

const STARTERS = [
  'How do I build a college list that actually fits me?',
  'What should I be doing this summer?',
  'Read my essay idea and tell me if it is any good.',
  'How do I ask a teacher for a recommendation letter?',
];

function cleanSage(text) {
  let t = String(text);
  t = t.replace(/^#{1,6}\s+/gm, '');
  t = t.replace(/[*_`~]{1,3}/g, '');
  t = t.replace(/^\s*[-•]\s+/gm, '');
  t = t.replace(/^-{3,}\s*$/gm, '');
  t = t.replace(/—|–/g, ', ');
  t = t.replace(/[ \t]{2,}/g, ' ').trim();
  return t;
}

export default function SageChat() {
  // Profile context is assembled server side in sage-ask now, so this page
  // only needs the email to write the conversation log.
  const { email } = useProfile();
  const {
    subscription, hasSage, isPastDue, isCanceling,
    isLoadingSubscription, refetchSubscription,
  } = useSubscription();
  const [params, setParams] = useSearchParams();
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [thinking, setThinking] = useState(false);
  const [loading, setLoading] = useState(true);
  const [billingError, setBillingError] = useState('');
  const endRef = useRef(null);

  const checkout = params.get('checkout');

  // Stripe redirects back here the instant payment succeeds, but the webhook
  // that actually grants access lands a moment later. Poll briefly so the user
  // is not told to pay again for something they just bought.
  useEffect(() => {
    if (checkout !== 'success' || hasSage) return undefined;
    let tries = 0;
    const id = setInterval(() => {
      tries += 1;
      refetchSubscription();
      if (tries >= 10) clearInterval(id);
    }, 1500);
    return () => clearInterval(id);
  }, [checkout, hasSage, refetchSubscription]);

  useEffect(() => {
    if (!hasSage) { setLoading(false); return; }
    (async () => {
      try {
        const rows = await base44.entities.SageMessage.list('created_date', 200);
        setMessages(Array.isArray(rows) ? rows : []);
      } catch {
        setMessages([]);
      }
      setLoading(false);
    })();
  }, [hasSage]);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages.length, thinking]);

  const ask = async (text) => {
    const question = (text ?? input).trim();
    if (!question || thinking || !hasSage) return;
    setInput('');
    setThinking(true);

    const optimistic = { id: `local-${Date.now()}`, role: 'user', content: question };
    setMessages((m) => [...m, optimistic]);

    try {
      base44.entities.SageMessage.create({ user_email: email, role: 'user', content: question }).catch(() => {});

      // The answer is generated by the sage-ask backend function, which checks
      // the Subscription table before it will respond. The `hasSage` guard
      // above is only there to keep the UI honest, it is not the paywall.
      // Conversation history and profile context are read server side, so
      // nothing here can be forged from the browser.
      const res = await base44.functions.invoke('sage-ask', { question });
      const answer = cleanSage(res?.data?.answer || '');

      setMessages((m) => [...m, { id: `local-a-${Date.now()}`, role: 'assistant', content: answer }]);
      base44.entities.SageMessage.create({ user_email: email, role: 'assistant', content: answer }).catch(() => {});
    } catch (err) {
      const data = err?.response?.data;
      // The subscription lapsed mid-session. Re-read it so the paywall comes
      // back up instead of leaving them typing into a dead box.
      if (data?.code === 'sage_not_subscribed') {
        refetchSubscription();
      }
      setMessages((m) => [
        ...m,
        {
          id: `err-${Date.now()}`,
          role: 'assistant',
          content: data?.error || 'Sage could not answer that just now. Try asking again in a moment.',
        },
      ]);
    }
    setThinking(false);
  };

  if (isLoadingSubscription) return <Spinner />;

  // The paywall is the whole page when there is no active subscription. Sage
  // is the one paid thing on Pathways, so this is the only gate in the app.
  if (!hasSage) {
    const notice =
      checkout === 'success'
        ? { tone: 'ok', text: 'Payment received. Confirming with Stripe now, this usually takes a few seconds.' }
        : checkout === 'cancel'
          ? { tone: 'ok', text: 'No charge was made. You can subscribe whenever you are ready.' }
          : isPastDue
            ? { tone: 'error', text: 'Your last payment did not go through, so Sage is paused. Updating your card will switch it straight back on.' }
            : null;
    return <SagePaywall notice={notice} />;
  }

  const manageBilling = async () => {
    setBillingError('');
    try {
      await openBillingPortal();
    } catch (err) {
      setBillingError(err.message);
    }
  };

  const renewalDate = subscription?.current_period_end
    ? new Date(subscription.current_period_end).toLocaleDateString(undefined, {
        month: 'long', day: 'numeric', year: 'numeric',
      })
    : null;

  return (
    <div className="flex flex-col" style={{ gap: 16 }}>
      <Seo title="Ask Sage | Pathways" description="Chat with Sage, your AI college and career advisor on Pathways, personalized to your grade, school, and goals." path="/app/sage" noindex />
      {checkout === 'success' && (
        <div
          className="card"
          style={{
            padding: '12px 16px', borderRadius: 18, gap: 0,
            background: 'var(--color-accent-2-100)', border: '1px solid var(--color-accent-2-400)',
          }}
        >
          <span className="flex items-center gap-3 flex-wrap" style={{ fontSize: 14 }}>
            You're subscribed to Sage. Ask it anything.
            <button
              type="button"
              className="btn btn-ghost"
              style={{ fontSize: 13, marginLeft: 'auto' }}
              onClick={() => setParams({})}
            >
              Dismiss
            </button>
          </span>
        </div>
      )}

      <div className="flex items-start gap-4 flex-wrap">
        <div style={{ flex: '1 1 340px' }}>
          <h1 style={{ fontSize: 'clamp(26px,3.2vw,36px)', margin: '0 0 6px' }}>Ask Sage anything.</h1>
          <p style={{ color: 'var(--color-neutral-800)', margin: 0, maxWidth: '56ch', lineHeight: 1.6 }}>
            Sage knows your grade, your school, and your goals, and answers like a mentor who has all the time in the world.
          </p>
        </div>
        <div className="flex flex-col items-end" style={{ gap: 4 }}>
          <button type="button" className="btn btn-secondary" style={{ fontSize: 13 }} onClick={manageBilling}>
            Manage subscription
          </button>
          {renewalDate && (
            <span style={{ fontSize: 11.5, color: 'var(--color-neutral-600)' }}>
              {isCanceling ? `Ends ${renewalDate}` : `Renews ${renewalDate}`}
            </span>
          )}
          {billingError && (
            <span style={{ fontSize: 11.5, color: 'var(--color-accent-700)', maxWidth: 220, textAlign: 'right' }}>
              {billingError}
            </span>
          )}
        </div>
      </div>

      <div className="card elev-sm" style={{ padding: 20, gap: 14, borderRadius: 26, minHeight: 420 }}>
        <div className="flex flex-col" style={{ gap: 12, flex: 1, overflowY: 'auto', maxHeight: 460, paddingRight: 4 }}>
          {loading ? (
            <span style={{ fontSize: 13.5, color: 'var(--color-neutral-600)' }}>Loading your conversation…</span>
          ) : messages.length === 0 ? (
            <div className="flex flex-col" style={{ gap: 10 }}>
              <span style={{ fontSize: 14, color: 'var(--color-neutral-700)' }}>Not sure where to start?</span>
              <div className="flex flex-col items-start" style={{ gap: 8 }}>
                {STARTERS.map((s) => (
                  <button
                    key={s}
                    type="button"
                    onClick={() => ask(s)}
                    className="btn btn-secondary text-left"
                    style={{ fontFamily: 'var(--font-body)', fontSize: 13.5, borderRadius: 18, padding: '9px 16px' }}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            messages.map((m) => {
              const mine = m.role === 'user';
              return (
                <div
                  key={m.id}
                  style={{
                    alignSelf: mine ? 'flex-end' : 'flex-start',
                    maxWidth: mine ? '78%' : '92%',
                    background: mine ? 'var(--color-accent)' : 'var(--color-bg)',
                    color: mine ? 'var(--color-bg)' : 'var(--color-text)',
                    padding: '11px 16px',
                    borderRadius: 22,
                    fontSize: 14.5,
                    lineHeight: 1.6,
                    whiteSpace: 'pre-wrap',
                  }}
                >
                  {m.content}
                </div>
              );
            })
          )}
          {thinking && (
            <span style={{ fontSize: 13.5, color: 'var(--color-neutral-600)', alignSelf: 'flex-start' }}>
              Sage is thinking…
            </span>
          )}
          <div ref={endRef} />
        </div>

        <form
          onSubmit={(e) => { e.preventDefault(); ask(); }}
          className="flex gap-2 items-end"
        >
          <textarea
            className="input"
            style={{ minHeight: 46, flex: 1 }}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask about applications, majors, essays, or scholarships…"
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); ask(); }
            }}
          />
          <button type="submit" className="btn btn-primary" disabled={thinking || !input.trim()}>
            Ask Sage
          </button>
        </form>
      </div>
    </div>
  );
}